main/urls.py
from django.urls import path
from .views import register_request, homepage, login_request, logout_request, user_profile
app_name = "main"

urlpatterns = [
    path("", homepage, name="homepage"),                  # /
    path("register/", register_request, name='register'), # /register/
    path("login/", login_request, name='login'),          # /login/
    path("logout/", logout_request, name='logout'),  # /login/
    path("user/<int:id>/userprofile/", user_profile, name="userprofile")  # /user/1/userprofile/

]

panopt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('photos.urls'))
]

photos/urls.py
from django.urls import path

from photos.views import gallery_list, gallery_details

app_name = "photos"
urlpatterns = [
    path("galleries/", gallery_list, name="list" ),
    path("galleries/<id>/", gallery_details, name="details" ),

]

posts/urls.py
from django.urls import path

from .views import post_list, post_details

app_name = "posts"
urlpatterns = [
    path("posts/", post_list, name="list" ),
    path("posts/<id>/", post_details, name="details" ),

]

main/models.py
from django.db import models

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    bio = models.TextField()

photos/models.py
from django.db import models

# Create your models here.


class Gallery(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to="gallercovers/%Y/%m/%d/")

    def __repr__(self):
        return self.title

posts/models.py
from django.db import models

# Create your models here.
from django.template.defaultfilters import slugify


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    content = models.TextField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __repr__(self):
        return f"{self.title} ({self.author})"

    def __str__(self):
        return self.__repr__()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from main.models import UserProfile


class BirdForm(forms.Form):
    name = forms.CharField()


class NewUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

# https://github.com/rkorzen/panopt

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ["bio"]


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea)

main/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
from main.forms import NewUserForm, UserProfileForm, ContactForm


def homepage(request):
    messages.add_message(request, messages.INFO, 'Hello world.')
    return render(
        request,
        template_name="base.html",
        context={}
    )


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.add_message(request, messages.SUCCESS, 'User registered.')
            messages.add_message(request, messages.INFO, 'User logged in.')
            return redirect("/")

    form = NewUserForm()
    return render(
        request=request,
        template_name="main/register.html",
        context={'register_form': form}
    )


def login_request(request):
    if request.method == "POST":
        # pobieramy dane z formularza
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            # sprawdzamy czy jest user z tymi danymi
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect("/")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(
        request=request,
        template_name="main/login.html",
        context={"login_form": form}
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You are successfully logged out")
    return redirect("/")


def user_profile(request, id):
    user = User.objects.get(pk=id)

    if hasattr(user, 'userprofile'):
        profile = user.profile
    else:
        profile = None
        form = UserProfileForm()

    if request.method == "POST":
        form = UserProfileForm(data=request.POST, instance=profile)
        if form.is_valid():
            profile.save()
            return redirect("/")

    if profile:
        form = UserProfileForm(instance=profile)

    print(form)
    return render(
        request,
        "main/userprofile.html",
        context={'form': form,
                 'userprofile': profile,
                 'puser': user
                 }
    )


def contact(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print("wysylka maila...", data)

    return render(
        request,
        'main/contact.html',
        {'form': form}
    )

photos/views.py
from django.shortcuts import render

# Create your views here.
from photos.models import Gallery


def gallery_list(request):
    galleries = Gallery.objects.all()

    return render(
        request,
        "photos/list.html",
        {"galleries": galleries}
    )

def gallery_details(request, id):
    gallery = Gallery.objects.get(pk=id)

    return render(
        request,
        "photos/details.html",
        {"gallery": gallery}
    )

posts/views.py
from django.shortcuts import render

# Create your views here.
from posts.models import Post


def post_list(request):
    posts = Post.objects.all()

    return render(
        request,
        "photos/list.html",
        {"posts": posts}
    )

def post_details(request, id):
    post = Post.objects.get(pk=id)

    return render(
        request,
        "photos/details.html",
        {"post": post}
    )

photos/templates/photos/details.html
{% extends 'base.html' %}

{% block content %}
    {{ gallery }}
{% endblock %}

photos/templates/photos/list.html
{% extends 'base.html' %}

{% block content %}
    {% for g in galleries %}
        {#        <a href="/galleries/{{ g.id }}">{{ g.title }}</a>      #}
        <a href="{% url 'photos:details' g.id %}">{{ g.title }}</a>
    {% endfor %}
{% endblock %}

posts/templates/posts/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

posts/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>

{% include "navbar.html" %}

{% comment %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endcomment %}
<div class="container">
{% bootstrap_messages %}

{% block content %}
    JAKAS TRESC W BLOKU
{% endblock %}
</div>
</body>
</html>

templates/main/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/main/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container py-5">

    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
{#        {% crispy login_form %}#}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    </div>


{% endblock %}

templates/main/register.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <div class="row">
        <div class="col-lg-3 col-s-1"></div>
        <div class="col-lg-6 col-s-10">
            {{ block.super }}
            <h1>Sign Up</h1>
            <form method="POST">
                {% csrf_token %}
                {#        {{ register_form.as_p }}#}
                {% bootstrap_form register_form %}

                <button type="submit">Register</button>
            </form>
        </div>
        <div class="col-lg-3 col-s-1"></div>
    </div>
{% endblock %}

templates/main/userprofile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>
    Profil uzytkownika {{ userprofile.user.username }}
    </h1>
    {{ userprofile.bio }}

    {% if user == puser %}

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Wyslij</button>
    </form>

    {% endif %}
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Panoptikum</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/register/">Register</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/logout/">Logout ({{ user }})</a>
                    </li>
                {% endif %}


            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>